package com.ylzinfo.service.his.mz.ws.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PrintService service = new PrintService();
 * PrintServiceSoap portType = service.getPrintServiceSoap();
 * portType.helloWorld(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PrintService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.10.100.14:8080/PrintService.asmx?wsdl")
public class PrintService extends Service {

	private final static URL PRINTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ylzinfo.service.his.mz.ws.webservice.PrintService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ylzinfo.service.his.mz.ws.webservice.PrintService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.10.100.14:8080/PrintService.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.10.100.14:8080/PrintService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PRINTSERVICE_WSDL_LOCATION = url;
	}

	public PrintService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PrintService() {
		super(PRINTSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"PrintService"));
	}

	/**
	 * 
	 * @return returns PrintServiceSoap
	 */
	@WebEndpoint(name = "PrintServiceSoap")
	public PrintServiceSoap getPrintServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"PrintServiceSoap"), PrintServiceSoap.class);
	}

	/**
	 * 
	 * @return returns PrintServiceSoap
	 */
	@WebEndpoint(name = "PrintServiceSoap12")
	public PrintServiceSoap getPrintServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"PrintServiceSoap12"), PrintServiceSoap.class);
	}

	/**
	 * 
	 * @return returns PrintServiceHttpGet
	 */
	@WebEndpoint(name = "PrintServiceHttpGet")
	public PrintServiceHttpGet getPrintServiceHttpGet() {
		return super.getPort(new QName("http://tempuri.org/",
				"PrintServiceHttpGet"), PrintServiceHttpGet.class);
	}

	/**
	 * 
	 * @return returns PrintServiceHttpPost
	 */
	@WebEndpoint(name = "PrintServiceHttpPost")
	public PrintServiceHttpPost getPrintServiceHttpPost() {
		return super.getPort(new QName("http://tempuri.org/",
				"PrintServiceHttpPost"), PrintServiceHttpPost.class);
	}

}
