package com.ylzinfo.service.his.mz.ws.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PrintServiceSoap", targetNamespace = "http://tempuri.org/")
public interface PrintServiceSoap {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
	@WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.HelloWorld")
	@ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.HelloWorldResponse")
	public String helloWorld();

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod(operationName = "OpenCon", action = "http://tempuri.org/OpenCon")
	@WebResult(name = "OpenConResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "OpenCon", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.OpenCon")
	@ResponseWrapper(localName = "OpenConResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.OpenConResponse")
	public int openCon();

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "PrintForm", action = "http://tempuri.org/PrintForm")
	@WebResult(name = "PrintFormResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "PrintForm", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.PrintForm")
	@ResponseWrapper(localName = "PrintFormResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.PrintFormResponse")
	public ArrayOfString printForm(
			@WebParam(name = "patientId", targetNamespace = "http://tempuri.org/") String patientId,
			@WebParam(name = "patientType", targetNamespace = "http://tempuri.org/") String patientType,
			@WebParam(name = "dtReg", targetNamespace = "http://tempuri.org/") String dtReg,
			@WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/") String dtEnd);

	/**
	 * 
	 * @param barcode
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "PrintForm_ByBarcode", action = "http://tempuri.org/PrintForm_ByBarcode")
	@WebResult(name = "PrintForm_ByBarcodeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "PrintForm_ByBarcode", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.PrintFormByBarcode")
	@ResponseWrapper(localName = "PrintForm_ByBarcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.PrintFormByBarcodeResponse")
	public ArrayOfString printFormByBarcode(
			@WebParam(name = "barcode", targetNamespace = "http://tempuri.org/") String barcode);

	/**
	 * 
	 * @param reqXml
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "Upload_ResultXml", action = "http://tempuri.org/Upload_ResultXml")
	@WebResult(name = "Upload_ResultXmlResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Upload_ResultXml", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.UploadResultXml")
	@ResponseWrapper(localName = "Upload_ResultXmlResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.UploadResultXmlResponse")
	public ArrayOfString uploadResultXml(
			@WebParam(name = "reqXml", targetNamespace = "http://tempuri.org/") String reqXml);

	/**
	 * 
	 * @param testType
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF_byID", action = "http://tempuri.org/ExportTestFormPDF_byID")
	@WebResult(name = "ExportTestFormPDF_byIDResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ExportTestFormPDF_byID", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFByID")
	@ResponseWrapper(localName = "ExportTestFormPDF_byIDResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFByIDResponse")
	public ArrayOfString exportTestFormPDFByID(
			@WebParam(name = "machineId", targetNamespace = "http://tempuri.org/") String machineId,
			@WebParam(name = "sampleId", targetNamespace = "http://tempuri.org/") String sampleId,
			@WebParam(name = "testdate", targetNamespace = "http://tempuri.org/") String testdate,
			@WebParam(name = "testType", targetNamespace = "http://tempuri.org/") TestType testType);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "ExportTestFormPDF_RT", action = "http://tempuri.org/ExportTestFormPDF_RT")
	@WebResult(name = "ExportTestFormPDF_RTResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ExportTestFormPDF_RT", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFRT")
	@ResponseWrapper(localName = "ExportTestFormPDF_RTResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFRTResponse")
	public byte[] exportTestFormPDFRT(
			@WebParam(name = "machineId", targetNamespace = "http://tempuri.org/") String machineId,
			@WebParam(name = "sampleId", targetNamespace = "http://tempuri.org/") String sampleId,
			@WebParam(name = "testdate", targetNamespace = "http://tempuri.org/") String testdate);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "ExportTestFormPDF_GM", action = "http://tempuri.org/ExportTestFormPDF_GM")
	@WebResult(name = "ExportTestFormPDF_GMResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ExportTestFormPDF_GM", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFGM")
	@ResponseWrapper(localName = "ExportTestFormPDF_GMResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFGMResponse")
	public byte[] exportTestFormPDFGM(
			@WebParam(name = "machineId", targetNamespace = "http://tempuri.org/") String machineId,
			@WebParam(name = "sampleId", targetNamespace = "http://tempuri.org/") String sampleId,
			@WebParam(name = "testdate", targetNamespace = "http://tempuri.org/") String testdate);

	/**
	 * 
	 * @param patientId
	 * @param path
	 * @param patientType
	 * @param patientSeq
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF_ByPatientSeq", action = "http://tempuri.org/ExportTestFormPDF_ByPatientSeq")
	@WebResult(name = "ExportTestFormPDF_ByPatientSeqResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ExportTestFormPDF_ByPatientSeq", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFByPatientSeq")
	@ResponseWrapper(localName = "ExportTestFormPDF_ByPatientSeqResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFByPatientSeqResponse")
	public ArrayOfString exportTestFormPDFByPatientSeq(
			@WebParam(name = "patientSeq", targetNamespace = "http://tempuri.org/") String patientSeq,
			@WebParam(name = "patientId", targetNamespace = "http://tempuri.org/") String patientId,
			@WebParam(name = "patientType", targetNamespace = "http://tempuri.org/") String patientType,
			@WebParam(name = "path", targetNamespace = "http://tempuri.org/") String path);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF", action = "http://tempuri.org/ExportTestFormPDF")
	@WebResult(name = "ExportTestFormPDFResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ExportTestFormPDF", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDF")
	@ResponseWrapper(localName = "ExportTestFormPDFResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.ExportTestFormPDFResponse")
	public ArrayOfString exportTestFormPDF(
			@WebParam(name = "patientId", targetNamespace = "http://tempuri.org/") String patientId,
			@WebParam(name = "patientType", targetNamespace = "http://tempuri.org/") String patientType,
			@WebParam(name = "dtReg", targetNamespace = "http://tempuri.org/") String dtReg,
			@WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/") String dtEnd);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetTestForm", action = "http://tempuri.org/GetTestForm")
	@WebResult(name = "GetTestFormResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTestForm", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetTestForm")
	@ResponseWrapper(localName = "GetTestFormResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetTestFormResponse")
	public ArrayOfString getTestForm(
			@WebParam(name = "patientId", targetNamespace = "http://tempuri.org/") String patientId,
			@WebParam(name = "patientType", targetNamespace = "http://tempuri.org/") String patientType,
			@WebParam(name = "dtReg", targetNamespace = "http://tempuri.org/") String dtReg,
			@WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/") String dtEnd);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetTestFormNew", action = "http://tempuri.org/GetTestFormNew")
	@WebResult(name = "GetTestFormNewResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTestFormNew", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetTestFormNew")
	@ResponseWrapper(localName = "GetTestFormNewResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetTestFormNewResponse")
	public ArrayOfString getTestFormNew(
			@WebParam(name = "patientId", targetNamespace = "http://tempuri.org/") String patientId,
			@WebParam(name = "patientType", targetNamespace = "http://tempuri.org/") String patientType,
			@WebParam(name = "dtReg", targetNamespace = "http://tempuri.org/") String dtReg,
			@WebParam(name = "dtEnd", targetNamespace = "http://tempuri.org/") String dtEnd);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns int
	 */
	@WebMethod(operationName = "EditPrinted", action = "http://tempuri.org/EditPrinted")
	@WebResult(name = "EditPrintedResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditPrinted", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.EditPrinted")
	@ResponseWrapper(localName = "EditPrintedResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.EditPrintedResponse")
	public int editPrinted(
			@WebParam(name = "machineId", targetNamespace = "http://tempuri.org/") String machineId,
			@WebParam(name = "sampleId", targetNamespace = "http://tempuri.org/") String sampleId,
			@WebParam(name = "testdate", targetNamespace = "http://tempuri.org/") String testdate);

	/**
	 * 
	 * @param reportid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportPrintstate", action = "http://tempuri.org/GetReportPrintstate")
	@WebResult(name = "GetReportPrintstateResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportPrintstate", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetReportPrintstate")
	@ResponseWrapper(localName = "GetReportPrintstateResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetReportPrintstateResponse")
	public String getReportPrintstate(
			@WebParam(name = "Reportid", targetNamespace = "http://tempuri.org/") String reportid);

	/**
	 * 
	 * @param barcode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportLockDoubt", action = "http://tempuri.org/GetReportLockDoubt")
	@WebResult(name = "GetReportLockDoubtResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportLockDoubt", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetReportLockDoubt")
	@ResponseWrapper(localName = "GetReportLockDoubtResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetReportLockDoubtResponse")
	public String getReportLockDoubt(
			@WebParam(name = "Barcode", targetNamespace = "http://tempuri.org/") String barcode);

	/**
	 * 
	 * @param patientseq
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetItemInfoFromUndoReport", action = "http://tempuri.org/GetItemInfoFromUndoReport")
	@WebResult(name = "GetItemInfoFromUndoReportResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetItemInfoFromUndoReport", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetItemInfoFromUndoReport")
	@ResponseWrapper(localName = "GetItemInfoFromUndoReportResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetItemInfoFromUndoReportResponse")
	public ArrayOfString getItemInfoFromUndoReport(
			@WebParam(name = "patientseq", targetNamespace = "http://tempuri.org/") String patientseq);

	/**
	 * 微生物全自动接种仪服务
	 * 
	 * @param sampleid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetHisItemInfo", action = "http://tempuri.org/GetHisItemInfo")
	@WebResult(name = "GetHisItemInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetHisItemInfo", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetHisItemInfo")
	@ResponseWrapper(localName = "GetHisItemInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.GetHisItemInfoResponse")
	public String getHisItemInfo(
			@WebParam(name = "sampleid", targetNamespace = "http://tempuri.org/") String sampleid);

	/**
	 * 
	 * @param answerid
	 * @param answername
	 * @param barcode
	 * @param answercon
	 * @param itemid
	 * @return returns int
	 */
	@WebMethod(operationName = "CriticalValueAlertFeedBack", action = "http://tempuri.org/CriticalValueAlertFeedBack")
	@WebResult(name = "CriticalValueAlertFeedBackResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CriticalValueAlertFeedBack", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.CriticalValueAlertFeedBack")
	@ResponseWrapper(localName = "CriticalValueAlertFeedBackResponse", targetNamespace = "http://tempuri.org/", className = "com.ylzinfo.service.his.mz.ws.webservice.CriticalValueAlertFeedBackResponse")
	public int criticalValueAlertFeedBack(
			@WebParam(name = "barcode", targetNamespace = "http://tempuri.org/") String barcode,
			@WebParam(name = "itemid", targetNamespace = "http://tempuri.org/") String itemid,
			@WebParam(name = "answername", targetNamespace = "http://tempuri.org/") String answername,
			@WebParam(name = "answercon", targetNamespace = "http://tempuri.org/") String answercon,
			@WebParam(name = "answerid", targetNamespace = "http://tempuri.org/") String answerid);

}
