package com.ylzinfo.service.his.mz.ws.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PrintServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PrintServiceHttpPost {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "HelloWorld")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String helloWorld();

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod(operationName = "OpenCon")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int openCon();

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "PrintForm")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString printForm(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId") String patientId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientType") String patientType,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtReg") String dtReg,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtEnd") String dtEnd);

	/**
	 * 
	 * @param barcode
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "PrintForm_ByBarcode")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString printFormByBarcode(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "barcode") String barcode);

	/**
	 * 
	 * @param reqXml
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "Upload_ResultXml")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString uploadResultXml(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "reqXml") String reqXml);

	/**
	 * 
	 * @param testType
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF_byID")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString exportTestFormPDFByID(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "machineId") String machineId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sampleId") String sampleId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "testdate") String testdate,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "testType") String testType);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "ExportTestFormPDF_RT")
	@WebResult(name = "base64Binary", targetNamespace = "http://tempuri.org/", partName = "Body")
	public byte[] exportTestFormPDFRT(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "machineId") String machineId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sampleId") String sampleId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "testdate") String testdate);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "ExportTestFormPDF_GM")
	@WebResult(name = "base64Binary", targetNamespace = "http://tempuri.org/", partName = "Body")
	public byte[] exportTestFormPDFGM(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "machineId") String machineId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sampleId") String sampleId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "testdate") String testdate);

	/**
	 * 
	 * @param patientId
	 * @param path
	 * @param patientType
	 * @param patientSeq
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF_ByPatientSeq")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString exportTestFormPDFByPatientSeq(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientSeq") String patientSeq,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId") String patientId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientType") String patientType,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "path") String path);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "ExportTestFormPDF")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString exportTestFormPDF(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId") String patientId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientType") String patientType,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtReg") String dtReg,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtEnd") String dtEnd);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetTestForm")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString getTestForm(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId") String patientId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientType") String patientType,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtReg") String dtReg,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtEnd") String dtEnd);

	/**
	 * 
	 * @param patientId
	 * @param dtReg
	 * @param dtEnd
	 * @param patientType
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetTestFormNew")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString getTestFormNew(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId") String patientId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientType") String patientType,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtReg") String dtReg,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dtEnd") String dtEnd);

	/**
	 * 
	 * @param testdate
	 * @param machineId
	 * @param sampleId
	 * @return returns int
	 */
	@WebMethod(operationName = "EditPrinted")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int editPrinted(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "machineId") String machineId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sampleId") String sampleId,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "testdate") String testdate);

	/**
	 * 
	 * @param reportid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportPrintstate")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportPrintstate(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Reportid") String reportid);

	/**
	 * 
	 * @param barcode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportLockDoubt")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportLockDoubt(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Barcode") String barcode);

	/**
	 * 
	 * @param patientseq
	 * @return returns com.ylzinfo.service.his.mz.ws.webservice.ArrayOfString
	 */
	@WebMethod(operationName = "GetItemInfoFromUndoReport")
	@WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
	public ArrayOfString getItemInfoFromUndoReport(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientseq") String patientseq);

	/**
	 * 微生物全自动接种仪服务
	 * 
	 * @param sampleid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetHisItemInfo")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getHisItemInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sampleid") String sampleid);

	/**
	 * 
	 * @param answerid
	 * @param answername
	 * @param barcode
	 * @param answercon
	 * @param itemid
	 * @return returns int
	 */
	@WebMethod(operationName = "CriticalValueAlertFeedBack")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int criticalValueAlertFeedBack(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "barcode") String barcode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "itemid") String itemid,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "answername") String answername,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "answercon") String answercon,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "answerid") String answerid);

}
